language: go

go: 
  - 1.9

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c "create role ptotest with login password 'helpful guide sheep train';" -U postgres
  - psql -c "create database ptotest;" -U postgres
  - psql -c "grant create on database ptotest to ptotest;" -U postgres

script:
  - go test github.com/mami-project/pto3-go
  - go test github.com/mami-project/pto3-go/papi